name: Ingest Development
on:
  push:
    paths:
      - 'ingest/**'
      - '.github/workflows/ingest_dev.yml'

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ env.GITHUB_SHA_SHORT }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Generate outputs
        run: |
          echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" | tee $GITHUB_ENV
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          pip install -U -q pip setuptools wheel
          pip install -r ingest/src/requirements.txt -r ingest/tests/requirements-dev.txt
          pytest -v ingest/tests
